#!/usr/bin/env ruby

require "optparse"
require "./dic_augmentor.rb"

dic = DicAugmentor.new
ARGV << '-h' if ARGV.empty?

OptionParser.new do |opts|
  opts.banner = "Usage: augment [options]"

  opts.on("-dDICT", "--dictionary=DICT", "Specify which built in dictionary to augment your Mac's spell checker with. Available options: tech, med") do |v|
    dic.augment_from_dict v
  end

  opts.on("-fPATH", "--file=PATH", "Specify a path to a newline separated list of words to augment your spell checker with") do |v|
    dic.augment_from_file v
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
  end
end.parse!
